import { ChevronLeft, ChevronRight, Minus, Plus, RotateCw, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { PdfPageItem } from './pdfTypes';
import { PdfThumbnailRail } from './PdfThumbnailRail';

export function PdfWorkspace({ pages, activePage, zoom, onZoomChange, onActivePageChange, onToggleSelection, onReorder, onRotate, onRemove }: { pages: PdfPageItem[]; activePage: number; zoom: number; onZoomChange: (zoom: number) => void; onActivePageChange: (page: number) => void; onToggleSelection: (page: number) => void; onReorder?: (from: number, to: number) => void; onRotate?: (page: number) => void; onRemove?: (page: number) => void }) {
  const current = pages.find((page) => page.pageNumber === activePage) || pages[0];
  const move = (direction: number) => onActivePageChange(Math.min(pages.length, Math.max(1, activePage + direction)));
  return <div className="rounded-xl border bg-muted/20 p-3"><div className="flex flex-wrap items-center justify-between gap-2 border-b pb-3"><div className="flex items-center gap-1"><Button size="icon" variant="outline" aria-label="Página anterior" disabled={activePage <= 1} onClick={() => move(-1)}><ChevronLeft /></Button><span className="min-w-20 text-center text-sm font-medium">Página {current?.pageNumber || 0} de {pages.length}</span><Button size="icon" variant="outline" aria-label="Próxima página" disabled={activePage >= pages.length} onClick={() => move(1)}><ChevronRight /></Button></div><div className="flex items-center gap-1"><Button size="icon" variant="ghost" aria-label="Reduzir zoom" onClick={() => onZoomChange(Math.max(50, zoom - 10))}><Minus /></Button><span className="w-12 text-center text-sm">{zoom}%</span><Button size="icon" variant="ghost" aria-label="Aumentar zoom" onClick={() => onZoomChange(Math.min(150, zoom + 10))}><Plus /></Button><Button size="icon" variant="ghost" aria-label="Girar página" onClick={() => current && onRotate?.(current.pageNumber)}><RotateCw /></Button><Button size="icon" variant="ghost" className="text-destructive" aria-label="Remover página" onClick={() => current && onRemove?.(current.pageNumber)}><Trash2 /></Button></div></div><div className="mt-3 grid gap-4 lg:grid-cols-[180px_minmax(0,1fr)]"><PdfThumbnailRail pages={pages} activePage={activePage} onActivePageChange={onActivePageChange} onToggleSelection={onToggleSelection} onReorder={onReorder} /><div className="flex min-h-[360px] items-center justify-center overflow-auto rounded-lg border bg-slate-200/60 p-4"><div style={{ transform: `scale(${zoom / 100})`, transformOrigin: 'center center' }} className="flex aspect-[0.707] w-[min(100%,520px)] items-center justify-center rounded-sm bg-white text-center text-muted-foreground shadow-lg transition-transform"><div><p className="text-lg font-semibold">Página {current?.pageNumber || 0}</p><p className="text-xs">Preview do PDF</p></div></div></div></div></div>;
}
