// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qywjbutxdklmhihscahy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5d2pidXR4ZGtsbWhpaHNjYWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTI3MjAsImV4cCI6MjA2NTUyODcyMH0.8GZhRVy0HdTO9Wzrh2lg1DE-yPGRnIvna_6OXPjf8HA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);